version: "3"
services:
  frontend:
    build:
      context: ./frontend
    image: somkiat/pets-front:v1
    ports:
      - 9999:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
      
  web:
    build:
      context: ./web
    image: somkiat/pets-web:v1
    ports:
      - 8888:80
    environment:
      - DB_USER=xxx
      - DB_PASWORD=xxx
  db:
    build:
      context: ./db
    image: somkiat/pets-db:v1