version: "3"
services:
  web:
    build:
      context: ./web
    image: somkiat/pets-web:v1
    ports:
      - 8888:80
    environment:
      - DB_USER=xxx
      - DB_PASWORD=xxx
  db:
    build:
      context: ./db
    image: somkiat/pets-db:v1